language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-20.0.0
    - android-19
    - sys-img-x86-android-19
  licenses:
    - 'android-sdk-license-.+'

before_script:
  - ./script/emulator-start-wait.sh

before_install:
  - ./setup.sh

script:
  - mvn clean install
